services:
  fp-stats:
    image: nicepenguin/fp-stats:latest
    container_name: fp-stats
    volumes:
      - /mnt/appdata/fp-stats/configdata:/configdata
      - /mnt/appdata/fp-stats/output:/plots
    restart: unless-stopped
    environment:
      - TZ=UTC
